### ISSUE TITLE
`table.sort` does not inspect the hash part

### ISSUE THREAD

**Issue by Wojbie** [SquidDev/Cobalt#58]
Found this issue when i was messing with table.sort.
```lua
print("first")
local test = {"d","a","b","c"}
table.sort(test, function(a, b) return a < b end)
for k, v in ipairs(test) do
  print(k, v)
end
print("second")
local test = {[1]="d",[2]="a",[3]="b",[4]="c"}
table.sort(test, function(a, b) return a < b end)
for k, v in ipairs(test) do
  print(k, v)
end
```
This code generates this output in Cobalt. As one can see second table is not getting sorted... 
![obraz](https://user-images.githubusercontent.com/5893536/131593399-80509c8a-d44d-4c1a-b82a-38ab0a0d9a05.png)
While in other lua instances it creates:
```
first
1    a
2    b
3    c
4    d
second
1    a
2    b
3    c
4    d
```

This seems to imply there is something wrong with table related logic in Cobalt.

**Comment by SquidDev** [comment]
Well, this is embarrassing. It only uses the array part. I suspect the fix here is to shift everything to use `rawget`/`rawset` instead of indexing `array` directly.

https://github.com/SquidDev/Cobalt/blob/859205c40f1366dcf1bfff71ef7cd38038bcb221/src/main/java/org/squiddev/cobalt/LuaTable.java#L645-L675

**Comment by SquidDev** [comment]
Technically we should actually be supporting `__index`/`__newindex` here. Ughrhrhrrh.
